Export noisecapture gain to server (#41)
* Export gain in zip file, coverage of unit test

* export and parse gain value

* fix travis script

* Fix travis issue

* travis sdk android

* need sdk 23

* travis upgrade build tools

* try tools

Error: Ignoring unknown package filter 'build-tools-23.0.2'
Warning: The package filter removed all packages. There is nothing to
install.
Please consider trying to update again without a package filter.

* ask gradl to use last available andriod tools

* sosfilter dependency as subproject

* check with last build tools version

* change script

* upgrade to java 8, as geoserver is compiled using java8

* too much dependency to link noisecapture with geoserver parser test